language: node_js

node_js:
  - "6.2"

notifications:
  slack: sveasolar:SlVckMxaT9VUoDiPEA5mcutq
  email: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8