language: node_js

node_js:
  - "6.2"


notifications:
  email: false
  slack:
    rooms:
    - sveasolar:SlVckMxaT9VUoDiPEA5mcutq#code-builds
    on_success: change
    on_failure: always

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8